import {FACES} from './font-data';

/**
 * Registers the five type faces.
 *
 * The faces are base64-inlined into the bundle (src/lib/font-data.ts,
 * generated by scripts/embed_fonts.py). They are copied verbatim from the
 * completed TASCAM Sonicview reel project, which inherited them from the MOTU
 * UltraLite-mk5 / 828 reel — this project inherits that type system rather
 * than inventing one.
 *
 * WHY CSS AND NOT THE FontFace API.
 *
 * Two earlier approaches both stalled a full 2,640-frame render:
 *
 *   1. `staticFile()` + `new FontFace(...).load()` behind delayRender — the
 *      fetch stalled under render concurrency and the "load-fonts" handle
 *      timed out on frames 549-550.
 *   2. base64 data URIs + the same FontFace API — still timed out, in pairs,
 *      roughly every 720 frames, i.e. whenever Remotion recycled the render
 *      page. The `.load()` promise simply never settled on those fresh pages.
 *      Remotion retried and the frames came out correct, but each stall cost
 *      ~118 s of wall time.
 *
 * Injecting a plain `@font-face` stylesheet removes the promise from the
 * picture altogether. The bytes are already in the document, so there is no
 * network step and nothing asynchronous to hang: the style engine has
 * everything it needs the moment the rule is parsed. `font-display: block`
 * keeps the browser from painting a fallback while it decodes.
 *
 * Because nothing is awaited, there is no delayRender handle to leak, and a
 * recycled page re-injects the same <style> element deterministically.
 */

const STYLE_ID = 'tlm107-faces';

export const loadFonts = (): void => {
  if (typeof document === 'undefined') return;
  if (document.getElementById(STYLE_ID)) return;

  const css = FACES.map(
    (f) => `@font-face{
  font-family:"${f.family}";
  font-style:normal;
  font-weight:${f.weight};
  font-display:block;
  src:url(data:font/woff2;base64,${f.data}) format("woff2");
}`,
  ).join('\n');

  const el = document.createElement('style');
  el.id = STYLE_ID;
  el.textContent = css;
  document.head.appendChild(el);
};
