#!/usr/bin/env python3
"""Regenerates src/lib/font-data.ts by base64-inlining public/fonts/*.woff2.

Run after changing any font file. See src/lib/fonts.ts for why the faces are
inlined rather than fetched at render time.
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FACES = [
    ("BarlowCondensed", "bc-600.woff2", "600"),
    ("BarlowCondensed", "bc-700.woff2", "700"),
    ("BarlowCondensed", "bc-800.woff2", "800"),
    ("Inter", "inter-var.woff2", "100 900"),
    ("JetBrainsMono", "jbm-var.woff2", "100 800"),
]

HEADER = """// GENERATED by scripts/embed_fonts.py -- do not edit by hand.
//
// The five woff2 faces, base64-inlined.
//
// They were previously fetched from public/fonts via staticFile(). Under
// render concurrency that fetch stalled and the delayRender("load-fonts")
// handle timed out on frames 549-550 of a full render, which risks a frame
// being painted with a fallback face. Inlining removes the network step
// entirely, so the FontFace promises resolve immediately and no frame can
// race the loader.

export type Face = {family: string; weight: string; data: string};

export const FACES: Face[] = ["""


def main() -> int:
    lines = [HEADER]
    total = 0
    for family, filename, weight in FACES:
        path = os.path.join(ROOT, "public", "fonts", filename)
        with open(path, "rb") as fh:
            data = base64.b64encode(fh.read()).decode()
        total += len(data)
        lines.append(f"  {{family: '{family}', weight: '{weight}', data: '{data}'}},")
    lines.append("];")
    out = os.path.join(ROOT, "src", "lib", "font-data.ts")
    with open(out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote src/lib/font-data.ts ({total / 1024:.0f} KB base64, {len(FACES)} faces)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
